import Footer from "./Footer";
import NavBar from "./Nav";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div className="container">
      <Head>
        <title>XL Cheat Sheeets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
